version: "3.3"
services:
  committee-mongo_spot:
    image: mongo:7.0.0-rc6
    container_name: committee_mongo_test_spot
    restart: always
    ports:
      - 27019:27017
    volumes:
      - ../data/mongo_db/db:/data/db
      - ../data/mongo_db/log:/var/log/mongodb
      - ../data/mongo_db/config:/etc/mongo
      #environment:
      #MONGO_INITDB_ROOT_USERNAME: oker
      #MONGO_INITDB_ROOT_PASSWORD: oker
