# simple prover or aggregator
worker_name = "4090-8"
log_dir = "data/logs"
log_level = "info"

[prover]
# Interval of notifying about an ongoing job in ms.
heartbeat_interval = 1000
# Interval between the prover rounds in ms.
cycle_wait = 5000
# Timeout for the requests to the prover server in milli seconds.
request_timeout = 15000
# Flag for dying after proving cycle
die_after_proof = false
prepare_data_interval = 1000
data_dir = "./data"
debug_file=false
# used to choose which type of proofs to create
#prefer_proof_type = "guest"
blocks_per_round = 2
threads = 2
circuit_version="dev-1.6.4"
cache_pkey = true

[prover.api]
url = "https://exchaintmrpc.okex.org/api/v1/zkdex/layer2/testnet/spot/scheduler"
port = 0
secret_auth = "abc"

[prover.db]
mongo="mongodb://localhost:27019"
pool_max_size=32

[promethues]
enable = false
port = "7009"
